server:
  port: 8084

spring:
  application:
    name: shop-goods-web
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.31.196
    port: 5672
    username: yuchen
    password: 150211
    virtual-host: /shop
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15