server:
  port: 8083

spring:
  application:
    name: search-service
  elasticsearch:
    rest:
      uris: 192.168.31.196:9200
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.31.196
    port: 5672
    username: yuchen
    password: 150211
    virtual-host: /shop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
