server:
  port: 8081

spring:
  application:
    name: shop-item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useSSL=false
    username: root
    password: supreme150211
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.31.196
    port: 5672
    username: yuchen
    password: 150211
    template:
      exchange: SHOP.ITEM.EXCHANGE
    virtual-host: /shop
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.item.pojo
