server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
spring:
  redis:
    host: 192.168.31.196
  application:
    name: shop-cart-service
shop:
  jwt:
    pubKeyPath: /Users/liuyuchen/Desktop/ShopResource/rsa/rsa.pub # 公钥地址
    cookieName: SHOP_AUTH